version: "3.8"

services:
  postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: lemmy
      POSTGRES_DB: lemmy
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal
    secrets:
      - POSTGRES_PASSWORD
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lemmy -d lemmy -h 127.0.0.1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

  pictrs:
    image: asonix/pictrs:0.5.17-pre.9
    hostname: pictrs
    user: "991:991"
    volumes:
      - pictrs_data:/mnt
    networks:
      - internal
      - infra_reverse-proxy
    secrets:
      - PICTRS_API_KEY
    command:
      - /bin/sh
      - -lc
      - |
        export PICTRS__SERVER__API_KEY="$(cat /run/secrets/PICTRS_API_KEY)"
        exec /usr/local/bin/pict-rs -p /mnt
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/ >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 20s

  lemmy:
    image: dessalines/lemmy:0.19.14
    hostname: lemmy
    environment:
      LEMMY_CONFIG_LOCATION: /config/lemmy.hjson
    configs:
      - source: lemmy_hjson_template
        target: /config/lemmy.hjson.template
      - source: render_lemmy_config_sh
        target: /usr/local/bin/render-lemmy-config.sh
        mode: 0555
    secrets:
      - POSTGRES_PASSWORD
      - PICTRS_API_KEY
      - LEMMY_ADMIN_USERNAME
      - LEMMY_ADMIN_PASSWORD
      - LEMMY_ADMIN_EMAIL
    command:
      - /bin/sh
      - -lc
      - |
        /usr/local/bin/render-lemmy-config.sh
        exec lemmy_server
    depends_on:
      - postgres
      - pictrs
    networks:
      - internal
      - infra_reverse-proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8536/api/v3/site >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.14
    environment:
      LEMMY_UI_LEMMY_INTERNAL_HOST: lemmy:8536
      LEMMY_UI_LEMMY_EXTERNAL_HOST: ${LEMMY_HOSTNAME}
      LEMMY_UI_HTTPS: "true"
      LEMMY_UI_DEBUG: "false"
    depends_on:
      - lemmy
    networks:
      - internal
      - infra_reverse-proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:1234/ >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  internal:
    driver: overlay
  infra_reverse-proxy:
    external: true

volumes:
  postgres_data:
  pictrs_data:

configs:
  lemmy_hjson_template:
    file: ./lemmy.hjson.template
  render_lemmy_config_sh:
    file: ./render-lemmy-config.sh

secrets:
  POSTGRES_PASSWORD:
    external: true
  PICTRS_API_KEY:
    external: true
  LEMMY_ADMIN_USERNAME:
    external: true
  LEMMY_ADMIN_PASSWORD:
    external: true
  LEMMY_ADMIN_EMAIL:
    external: true